apiVersion: v1
data:
  KC_DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmRfMTIzIQ==
  KC_DB_URL_DATABASE: a2V5Y2xvYWs=
  KC_DB_URL_HOST: cG9zdGdyZXNxbC1zbmFwc2hvdA==
  KC_DB_URL_PORT: NTQzMg==
  KC_DB_USERNAME: a2V5Y2xvYWs=
  KC_FOLIO_BE_ADMIN_CLIENT_SECRET: U2VjcmV0UGFzc3dvcmQ=
  KC_HTTPS_KEY_STORE_PASSWORD: U2VjcmV0UGFzc3dvcmQ=
  KEYCLOAK_ADMIN_PASSWORD: U2VjcmV0UGFzc3dvcmQ=
  KEYCLOAK_ADMIN_USER: YWRtaW4=
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque