apiVersion: v1
data:
  KONG_ADMIN_USER: a29uZ19hZG1pbg==
  KONG_PASSWORD: YWRtaW4=
  KONG_PG_DATABASE: a29uZw==
  KONG_PG_HOST: cG9zdGdyZXNxbC1zbmFwc2hvdA==
  KONG_PG_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmRfMTIzIQ==
  KONG_PG_PORT: NTQzMg==
  KONG_PG_USER: a29uZw==
  KONG_URL: aHR0cDovL2tvbmctYWRtaW4tYXBpLXNuYXBzaG90
kind: Secret
metadata:
  name: kong-credentials
type: Opaque